name: Linux Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Install packages
      run: sudo apt-get install expat libgmp-dev libpopt-dev 
    - name: tag version date
      run: ./tag.sh
    - name: build spot
      run: ./build_openmpi.sh
    - name: list built files
      run: ls -lah website/
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: website/ # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch 
          single-commit: true
